# Generated by Django 3.1.2 on 2020-10-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_date', models.CharField(max_length=30)),
                ('proj_group', models.CharField(max_length=30)),
                ('proj_topic', models.TextField()),
                ('proj_overview', models.TextField()),
                ('proj_summary', models.TextField()),
            ],
        ),
    ]
