# Generated by Django 3.1.2 on 2020-10-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_group', models.TextField()),
                ('award_host', models.TextField()),
                ('award_result', models.TextField()),
            ],
        ),
    ]
