# Generated by Django 3.1.2 on 2020-10-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siaApp', '0002_awardlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awardlist',
            old_name='award_group',
            new_name='award_contest',
        ),
    ]
