# Generated by Django 3.1.2 on 2020-10-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaApp', '0003_auto_20201017_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardlist',
            name='award_date',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
