# Generated by Django 3.1.2 on 2020-10-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaApp', '0005_auto_20201017_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_group', models.TextField()),
                ('activities_content', models.TextField()),
                ('activities_duration', models.TextField()),
            ],
        ),
    ]
