# Generated by Django 3.1.2 on 2020-11-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaApp', '0006_activitieslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='proj_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
